wandb_version: 1

project_name:
  desc: null
  value: CVPR24
project_desc:
  desc: null
  value: cvpr new try.
seed:
  desc: null
  value: 3407
verbose:
  desc: null
  value: false
wandb:
  desc: null
  value: false
runtimes:
  desc: null
  value: 1
experiment_name:
  desc: null
  value: emnist
views:
  desc: null
  value: 2
note:
  desc: null
  value: disentangling
backbone:
  desc: null
  value:
    type: cnn
    normalization: batch
    init_method: xavier
dataset:
  desc: null
  value:
    name: EdgeMnist
    root: MyData
    class_num: 10
training_augmentation:
  desc: null
  value:
    enable: true
    crop_size: 32
    hflip: true
    random_resized_crop:
      size: 32
      scale:
      - 0.2
      - 1.0
    color_jitter_random_apply:
      p: 0.8
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
    random_grayscale:
      p: 0.2
valid_augmentation:
  desc: null
  value:
    crop_size: 32
train:
  desc: null
  value:
    epochs: 100
    batch_size: 256
    optim: adamw
    devices:
    - 0
    lr: 0.0005
    num_workers: 8
    save_log: true
    log_dir: ./experiments/emnist
    evaluate: 1
    scheduler: consine
    lr_decay_rate: 0.1
    lr_decay_epochs: 30
    samples_num: 8
    resume: false
    ckpt_path: ''
    use_ddp: false
    masked_ratio: 0.7
    mask_patch_size: 2
    mask_view: false
    mask_view_ratio: 0.15
    val_mask_view: true
    val_mask_view_ratio: 0.5
disent:
  desc: null
  value:
    hidden_size: 100
    alpha: 0.05
    mi_w: 0.01
vspecific:
  desc: null
  value:
    in_channel: 1
    v_dim: 10
    ch_mult:
    - 1
    - 2
    - 4
    block_size: 8
    basic_hidden_dim: 16
    latent_ch: 8
    num_res_blocks: 3
    best_view: 0
    kld_weight: 0.5
    model_path: ./experiments/emnist/final_model-3407
eval:
  desc: null
  value:
    model_path: ./mrdd-weights/emnist.pth
consistency:
  desc: null
  value:
    continous: true
    c_dim: 10
    in_channel: 1
    ch_mult:
    - 1
    - 2
    - 4
    block_size: 8
    basic_hidden_dim: 16
    latent_ch: 8
    num_res_blocks: 3
    kld_weight: 1.0
    alpha: 1.0
    temperature: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729512430
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.17.6
      8:
      - 3
      - 5
      13: windows-amd64
