experiment_name: "rmrdd-emnist"
views: 2
wandb: false
dataset:
  class_num: 10
  name: 'EdgeMnist'
  root: 'MyData'


train:
  epochs: 100
  use_ddp: false
  devices: [0]
  batch_size: 1024 # 64, 128, 512, 1024
  num_workers: 8
  lr: 0.001
  optim: "adamw"
  evaluate: 1
  scheduler: 'consine'
  samples_num: 8
  resume: false
  masked_ratio: 0.7
  mask_patch_size: 4



vspecific:
  v_dim: 10
  latent_ch: 8
  num_res_blocks: 3
  block_size: 8
  in_channel: 1
  basic_hidden_dim: 16
  ch_mult: [1, 2, 4]
  kld_weight: 0.5
  best_view: 0
  model_path: './experiments/EdgeMNIST/specific-v10/best-6422-99-3407.pth'


consistency:
  continous: True
  c_dim: 10
  in_channel: 1
  ch_mult: [ 1, 2, 4 ]
  block_size: 8
  basic_hidden_dim: 16
  latent_ch: 8
  num_res_blocks: 3
  kld_weight: 1.0
  alpha: 1.0
  temperature: 0.5

disent:
  hidden_size: 100
  mi_w: 0.001







